server:
  port: 9090
# 日志配置
logging:
  level:
    root: info
  file:
    name: plg_single-wisdom-farm-log/wisdom-farm.log
  logback:
    rollingpolicy:
      max-history: 30

# 数据源配置
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false